---
- name: System Update, Upgrade, and Clean Up
  hosts: all
  become: true
  tasks:
    # Update apt cache
    - name: 1.Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    # Perform a distribution upgrade
    - name: 2.Perform distribution upgrade
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    # Clean up unused packages and dependencies
    - name: 3.Clean up unused packages and dependencies
      ansible.builtin.apt:
        state: absent
        autoremove: yes
        autoclean: yes

    # Verify system status after updates
    - name: 4.Verify system is updated and clean
      command: "apt list --upgradable"
      register: updates_status
      changed_when: false

    - name: 5.Display remaining updates (if any)
      debug:
        var: updates_status.stdout_lines