---
- name: System Update, Upgrade, and Clean Up with Validation
  hosts: all
  become: true
  vars:
    # Fetch required environment variables
    admin_vps_user_name: "{{ lookup('env', 'ADMIN_VPS_USER_NAME') }}"  # Admin User Name
    admin_vps_password: "{{ lookup('env', 'ADMIN_VPS_USER_PASSWORD') }}"  # Admin Password
  tasks:
    # Step 4: Check if the user already exists and create if not
    - name: Check if the user already exists
      getent:
        database: passwd
        key: "{{ admin_vps_user_name }}"
      register: user_exists
      ignore_errors: true

    - name: Create user if it does not exist
      user:
        name: "{{ admin_vps_user_name }}"
        password: "{{ admin_vps_password | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes
        state: present
      when: user_exists.failed or user_exists is not defined