- name: Give permissions for new user
  hosts: all
  become: true
  vars:
    admin_vps_user_name: "{{ lookup('env', 'ADMIN_VPS_USER_NAME') }}"  # Admin User Name
  tasks:
    # Ensure sudoers.d directory exists and has proper permissions
    - name: 1. Ensure sudoers.d directory exists and has proper permissions
      file:
        path: /etc/sudoers.d
        state: directory
        mode: '0755'
        owner: root
        group: root

    # Grant sudo access to the user with validation (password required for sudo)
    - name: 2. Grant sudo access to the user with validation
      copy:
        content: "{{ admin_vps_user_name }} ALL=(ALL) ALL\n"  # No NOPASSWD here, so password will be required
        dest: "/etc/sudoers.d/{{ admin_vps_user_name }}"
        mode: '0440'
        owner: root
        group: root
        validate: '/usr/sbin/visudo -cf %s'  # Ensures the sudoers file is valid before applying
