- name: Give permissions for new user
  hosts: all
  become: true
  vars:
    admin_vps_user_name: "{{ lookup('env', 'ADMIN_VPS_USER_NAME') }}"  # Admin User Name
  tasks:
    # Ensure sudoers.d directory exists and has proper permissions
    - name: Ensure sudoers.d directory exists and has proper permissions
      file:
        path: /etc/sudoers.d
        state: directory
        mode: '0755'
        owner: root
        group: root

    # Remove any conflicting sudoers file for the user (if it exists)
    - name: Remove conflicting sudoers file for the user
      file:
        path: "/etc/sudoers.d/{{ admin_vps_user_name }}"
        state: absent
      ignore_errors: yes  # Ignore if file doesn't exist

    # Grant sudo access to the user (no password required) using lineinfile
    - name: Grant sudo access to the user (NOPASSWD)
      lineinfile:
        path: "/etc/sudoers.d/{{ admin_vps_user_name }}"
        line: "{{ admin_vps_user_name }} ALL=(ALL) NOPASSWD: ALL"
        create: yes  # Create the file if it doesn't exist
        mode: '0440'
        owner: root
        group: root
        validate: '/usr/sbin/visudo -cf %s'  # Ensures sudoers file is valid before applying
        insertafter: EOF
      when: admin_vps_user_name is defined