---
- name: Generate SSH RSA key pair and assign it to a new user
  hosts: localhost
  vars:
    target_user: "cmtuser"  # The username you want to create
    target_server: "cmt_database"  # The target server to manage

  tasks:
    - name: Generate SSH RSA key pair
      openssh_keypair:
        path: "/tmp/my_rsa_key"
        type: rsa
        size: 2048
        force: yes
      register: ssh_keypair

    - name: Store the private key in Semaphore Key Store
      semaphore_key_store:
        name: "cmt_database_ssh_key"
        value: "{{ lookup('file', '/tmp/my_rsa_key') }}"
        type: secret

    - name: Create a new user on the target server
      user:
        name: "{{ target_user }}"
        state: present
        create_home: yes  # Create home directory for the user
        shell: /bin/bash
      delegate_to: "{{ target_server }}"

    - name: Add SSH public key to the newly created user
      authorized_key:
        user: "{{ target_user }}"
        key: "{{ lookup('file', '/tmp/my_rsa_key.pub') }}"
        state: present
      delegate_to: "{{ target_server }}"
