---
- name: Install and configure MariaDB
  hosts: web_servers
  become: true
  tasks:
    - name: Ensure firewalld is enabled
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Allow traffic on port 22 (SSH) through the firewall (firewalld)
      ansible.builtin.command:
        cmd: firewall-cmd --zone=public --add-port=22/tcp --permanent

    - name: Allow traffic on port 3306 (MariaDB) through the firewall (firewalld)
      ansible.builtin.command:
        cmd: firewall-cmd --zone=public --add-port=3306/tcp --permanent

    - name: Reload firewalld to apply changes
      ansible.builtin.command:
        cmd: firewall-cmd --reload

    - name: Ensure MariaDB server is installed
      ansible.builtin.apt:
        name: mariadb-server
        state: present
        update_cache: yes
        force: yes

    - name: Ensure MariaDB service is running
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    - name: Configure MariaDB to listen on all IP addresses
      ansible.builtin.lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        create: yes

    - name: Restart MariaDB to apply new configuration
      ansible.builtin.systemd:
        name: mariadb
        state: restarted
