---
- name: Install and configure MariaDB
  hosts: web_servers
  become: true
  tasks:
    - name: Ensure iptables is installed
      ansible.builtin.yum:
        name: iptables
        state: present

    - name: Allow traffic on port 22 (SSH) through iptables
      ansible.builtin.command:
        cmd: iptables -A INPUT -p tcp --dport 22 -j ACCEPT

    - name: Allow traffic on port 3306 (MariaDB) through iptables
      ansible.builtin.command:
        cmd: iptables -A INPUT -p tcp --dport 3306 -j ACCEPT

    - name: Save iptables rules
      ansible.builtin.command:
        cmd: service iptables save

    - name: Ensure MariaDB server is installed
      ansible.builtin.apt:
        name: mariadb-server
        state: present
        update_cache: yes
        force: yes

    - name: Ensure MariaDB service is running
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    - name: Configure MariaDB to listen on all IP addresses
      ansible.builtin.lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        create: yes

    - name: Restart MariaDB to apply new configuration
      ansible.builtin.systemd:
        name: mariadb
        state: restarted
