---
- name: Install and start MySQL
  hosts: my_servers  # Make sure this matches the group in your inventory
  become: true
  tasks:
    - name: Ensure MySQL is installed
      ansible.builtin.apt:
        name: mysql-server
        state: present
        update_cache: yes  # Update the apt cache
        force: yes  # Ensure the package is installed even if it's already there

    - name: Ensure MySQL service is running
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: true
