---
- name: Install and start MySQL
  hosts: my_servers  # Make sure this matches the group in your inventory
  become: true
  tasks:
    - name: Ensure MySQL is installed
      ansible.builtin.yum:
        name: mysql-server
        state: present
    - name: Ensure MySQL service is running
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: true
