---
- name: Create User Using Secure Password from Vault
  hosts: all
  become: true
  vars:
    user_credentials: "{{ lookup('semaphore', 'cmt_user') }}"

  tasks:
    - name: Fetch username from environment variable or defined input
      set_fact:
        user_name: "{{ user_credentials.name }}"
        user_password: "{{ user_credentials.password }}"

    - name: Fetch password from vault and hash it
      set_fact:
        user_password_hashed: "{{ user_password | password_hash('sha512') }}"

    - name: Create user with hashed password
      user:
        name: "{{ user_name }}"
        password: "{{ user_password_hashed }}"
        shell: /bin/bash
        create_home: yes

    - name: Confirm user creation
      debug:
        msg: "User {{ user_name }} has been created successfully."
