---
- name: Create User Using Secure Password from Vault
  hosts: all
  become: true

  tasks:
    - name: Fetch username and password from environment variables
      set_fact:
        user_name: "{{ lookup('env', 'USER_NAME') }}"
        user_password: "{{ lookup('env', 'USER_PASSWORD') }}"

    - name: Check if the user already exists
      getent:
        database: passwd
        key: "{{ user_name }}"
      register: user_exists
      ignore_errors: true

    - name: Create user if it does not exist
      user:
        name: "{{ user_name }}"
        password: "{{ user_password }}"
        shell: /bin/bash
        create_home: yes
        state: present
      when: user_exists.failed  # Only create the user if it doesn't exist

    - name: Ensure the sudoers directory exists
      file:
        path: "/etc/sudoers.d"
        state: directory
        mode: '0755'

    - name: Check if the sudoers file exists for the user
      stat:
        path: "/etc/sudoers.d/{{ user_name }}"
      register: sudoers_file

    - name: Create sudoers file if it does not exist
      file:
        path: "/etc/sudoers.d/{{ user_name }}"
        state: touch
        mode: '0440'
      when: not sudoers_file.stat.exists

    - name: Grant sudo permissions to the user
      lineinfile:
        path: "/etc/sudoers.d/{{ user_name }}"
        state: present
        regexp: '^{{ user_name }}'
        line: '{{ user_name }} ALL=(ALL) NOPASSWD: ALL'

    - name: Set proper ownership and permissions for the sudoers file (chmod 440)
      file:
        path: "/etc/sudoers.d/{{ user_name }}"
        mode: '0440'
        state: file

    - name: Set proper ownership and permissions for home directory
      file:
        path: "/home/{{ user_name }}"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0755'
        state: directory

    - name: Confirm user creation (or existence)
      debug:
        msg: "User {{ user_name }} already exists or has been created successfully with a pre-hashed password."
