---
- name: Create User Using Secure Password from Vault
  hosts: all
  become: true
  vars:
    vault_username: "{{ lookup('semaphore', 'cmt_user_name') }}"
    vault_password: "{{ lookup('semaphore', 'cmt_user_password') }}"

  tasks:
    - name: Fetch username from environment variable or defined input
      set_fact:
        user_name: "{{ vault_username }}"

    - name: Fetch password from vault and hash it
      set_fact:
        user_password_hashed: "{{ vault_password | password_hash('sha512') }}"

    - name: Create user with hashed password
      user:
        name: "{{ user_name }}"
        password: "{{ user_password_hashed }}"
        shell: /bin/bash
        create_home: yes

    - name: Confirm user creation
      debug:
        msg: "User {{ user_name }} has been created successfully."
