---
- name: Create User Using Environment Variables
  hosts: all
  become: true

  tasks:
    - name: Fetch username from environment variable
      set_fact:
        user_name: "{{ lookup('env', 'USER_NAME') }}"

    - name: Fetch password from environment variable
      set_fact:
        user_password: "{{ lookup('env', 'USER_PASSWORD') | password_hash('sha512') }}"

    - name: Create user with environment variables
      user:
        name: "{{ user_name }}"
        password: "{{ user_password }}"
        shell: /bin/bash
        create_home: yes

    - name: Confirm user creation
      debug:
        msg: "User {{ user_name }} has been created successfully."
