---
- name: Create User and Ensure Sudo Access
  hosts: all
  become: true  # Ensure we have root privileges to manage sudoers and other actions
  vars:
    user_name: "{{ lookup('env', 'USER_NAME') }}"  # Fetch username from environment
    user_password: "{{ lookup('env', 'USER_PASSWORD') }}"  # Fetch password from environment

  tasks:
    # Step 1: Check if the user already exists
    - name: Check if the user already exists
      getent:
        database: passwd
        key: "{{ user_name }}"
      register: user_exists
      ignore_errors: true  # Prevent failure if the user doesn't exist

    # Step 2: Create the user if it doesn't exist
    - name: Create user if it does not exist
      user:
        name: "{{ user_name }}"
        password: "{{ user_password | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes
        state: present
      when: user_exists.failed or user_exists is not defined

    # Ensure the user has sudo access in /etc/sudoers.d/{{ user_name }}
    - name: Grant sudo access to the user in /etc/sudoers.d
      copy:
        dest: "/etc/sudoers.d/{{ user_name }}"
        content: '{{ user_name }} ALL=(ALL) NOPASSWD: ALL'
        mode: '0440'
      validate: '/usr/sbin/visudo -cf %s'

    # Step 4: Set proper permissions for the home directory
    - name: Set proper ownership and permissions for the user's home directory
      file:
        path: "/home/{{ user_name }}"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0755'
        state: directory
      when: user_exists.failed or user_exists is not defined

    # Step 5: Confirm user creation or existence
    - name: Confirm user creation (or existence)
      debug:
        msg: "User {{ user_name }} has been created or already exists and has sudo access."
