---
- name: Create User Using Secure Password from Vault
  hosts: all
  become: true

  vars:
    # Retrieve user name and password from Vault
    user_credentials: "{{ lookup('ansible.builtin.vault', 'cmt_user.vault') }}"

  tasks:
    - name: Fetch username and password from vault
      set_fact:
        user_name: "{{ user_credentials.name }}"
        user_password: "{{ user_credentials.password }}"

    - name: Create user with secure password
      user:
        name: "{{ user_name }}"
        password: "{{ user_password }}"
        shell: /bin/bash
        create_home: yes
        state: present

    - name: Grant sudo permissions to the user
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^{{ user_name }}'
        line: '{{ user_name }} ALL=(ALL) NOPASSWD: ALL'

    - name: Set proper ownership and permissions for home directory
      file:
        path: /home/{{ user_name }}
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0755'
        state: directory

    - name: Confirm user creation and sudo access
      debug:
        msg: "User {{ user_name }} has been created with sudo access."
