---
- name: Create User Using Vault Secrets
  hosts: all
  become: true

  tasks:
    - name: Fetch username from Vault
      set_fact:
        user_name: "{{ lookup('vault', 'USER_NAME') }}"

    - name: Fetch password from Vault
      set_fact:
        user_password: "{{ lookup('vault', 'USER_PASSWORD') | password_hash('sha512') }}"

    - name: Create new user with Vault credentials
      user:
        name: "{{ user_name }}"
        password: "{{ user_password }}"
        shell: /bin/bash
        create_home: yes

    - name: Confirm user creation
      debug:
        msg: "User {{ user_name }} has been created successfully."
