---
- name: Create User Using Secure Password from Vault
  hosts: all
  become: true
  vars:
    vault_password_secret: "{{ lookup('cmt_usr', 'password') }}"

  tasks:

    - name: Fetch password from vault and hash it
      set_fact:
        user_password_hashed: "{{ vault_password_secret | password_hash('sha512') }}"

    - name: Confirm user creation
      debug:
        msg: "Print {{ user_password_hashed }} Print."
