---
- name: Print Environment Variables, Extra Vars, and Vault Secrets
  hosts: all
  become: false

  tasks:
    - name: Print all environment variables
      debug:
        msg: "Environment Variables: USER_NAME={{ lookup('env', 'USER_NAME') }} USER_PASSWORD={{ lookup('env', 'USER_PASSWORD') }}"

    - name: Print all extra-vars passed from the command line or Semaphore UI
      debug:
        msg: "Extra Vars: user_name={{ user_name }} user_password={{ user_password }}"

    - name: Print secrets from Vault
      debug:
        msg: "Vault Secrets: USER_NAME={{ lookup('semaphore', 'USER_NAME') }} USER_PASSWORD={{ lookup('semaphore', 'USER_PASSWORD') }}"

    - name: Print all known facts for debugging purposes
      debug:
        var: hostvars

    - name: Print all variables defined in the playbook or job
      debug:
        var: vars
