---
- name: Create User Using Secure Password from Vault
  hosts: all
  become: true

  tasks:
    - name: Fetch password from vault and hash it
      user:
      set_fact:
        name: "{{ lookup('env', 'USER_NAME') }}"
        password: "{{ lookup('env', 'USER_PASSWORD') | password_hash('sha512') }}"

    - name: Confirm user creation
      debug:
        msg: "Print {{ name }} {{ password }}Print."
