---
- name: Create User Using Secure Password from Vault
  hosts: all
  become: true

  tasks:
    - name: Fetch username and password from environment variables
      set_fact:
        name: "{{ lookup('env', 'USER_NAME') }}"
        password: "{{ lookup('env', 'USER_PASSWORD') }}"

    - name: Create user with the pre-hashed password
      user:
        name: "{{ name }}"
        password: "{{ password }}"
        shell: /bin/bash
        create_home: yes

    - name: Confirm user creation
      debug:
        msg: "User {{ name }} has been created successfully with a pre-hashed password."