---
- name: Create User Using Secure Password from Vault
  hosts: all
  become: true

  tasks:
    - name: Fetch username and password from environment variables
      set_fact:
        name: "{{ lookup('env', 'USER_NAME') }}"
        password: "{{ lookup('env', 'USER_PASSWORD') | password_hash('sha512') }}"

    - name: Confirm user creation and print username and password
      debug:
        msg: "Username: {{ name }} and Hashed Password: {{ password }}"
