---
- name: Create User Using Secure Password from Vault
  hosts: all
  become: true
  vars:
    vault_password_secret: "{{ lookup('cmtuser', 'new_user_password') }}"

  tasks:
    - name: Fetch username from environment variable or defined input
      set_fact:
        user_name: "{{ cmtuser_name }}"

    - name: Fetch password from vault and hash it
      set_fact:
        user_password_hashed: "{{ vault_password_secret | password_hash('sha512') }}"

    - name: Create user with hashed password
      user:
        name: "{{ user_name }}"
        password: "{{ user_password_hashed }}"
        shell: /bin/bash
        create_home: yes

    - name: Confirm user creation
      debug:
        msg: "User {{ user_name }} has been created successfully."
