---
- name: Access and print aaa variable
  hosts: all
  become: false

  tasks:
    - name: Print the aaa variable
      debug:
        msg: "The value of aaa is: {{ aaa }}"
    - name: Print the sss variable
      debug:
        msg: "The value of sss is: {{ sss }}"
