---
- name: Create User Using Extra Vars
  hosts: all
  become: true

  tasks:
    - name: Check if username and password are provided
      fail:
        msg: "Both 'user_name' and 'user_password' must be provided via --extra-vars."
      when: user_name is not defined or user_password is not defined

    - name: Create user with provided credentials
      user:
        name: "{{ user_name }}"
        password: "{{ user_password | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes

    - name: Confirm user creation
      debug:
        msg: "User {{ user_name }} has been created successfully."
