---
- name: Create User Using Secure Password from Vault
  hosts: all
  become: true

  tasks:
    - name: Fetch username and password from environment variables
      set_fact:
        user_name: "{{ lookup('env', 'USER_NAME') }}"
        user_password: "{{ lookup('env', 'USER_PASSWORD') }}"

    - name: Create user with the pre-hashed password
      user:
        name: "{{ user_name }}"
        password: "{{ user_password | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes
        state: present
        
    - name: Grant sudo permissions to the user
      lineinfile:
        path: /etc/sudoers.d/{{ user_name }}
        state: present
        regexp: '^{{ user_name }}'
        line: '{{ user_name }} ALL=(ALL) NOPASSWD: ALL'
        
    - name: Set proper permissions for sudoers file (chmod 440)
      file:
        path: /etc/sudoers.d/{{ user_name }}
        mode: '0440'
        state: file
        
    - name: Set proper ownership and permissions for home directory
      file:
        path: /home/{{ user_name }}
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0755'
        state: directory

    - name: Confirm user creation
      debug:
        msg: "User {{ user_name }} has been created successfully with a pre-hashed password."
        
