---
- name: Modify SSH configuration for secure access
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_sudo_pass: "{{ lookup('env', 'USER_PASSWORD') }}"
  
  tasks:
    - name: Backup the original sshd_config file
      copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.backup
        backup: yes

    - name: Modify or add specific SSH settings in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?{{ item.setting }}'  # Match the line with or without a comment (#)
        line: "{{ item.setting }} {{ item.value }}"  # Modify the line with the new value
        create: yes  # Add the setting if it does not exist
        backrefs: yes  # Use backreferences in the regexp (important for uncommenting)
      with_items:
        - { setting: "LogLevel", value: "VERBOSE" }
        - { setting: "MaxAuthTries", value: "6" }
        - { setting: "MaxSessions", value: "10" }
        - { setting: "PermitEmptyPasswords", value: "no" }
        - { setting: "PermitRootLogin", value: "no" }
      notify: Restart SSH service

    - name: Restart SSH service to apply changes
      systemd:
        name: sshd
        state: restarted
      when: ansible_facts['distribution'] == "Debian" or ansible_facts['distribution'] == "Ubuntu"

  handlers:
    - name: Restart SSH service
      systemd:
        name: sshd
        state: restarted
