---
- name: Modify SSH configuration for secure access
  hosts: all
  become: true
  become_method: sudo
  vars:
    ansible_sudo_pass: "{{ lookup('env', 'USER_PASSWORD') }}"
  
  tasks:
    - name: Backup the original sshd_config file
      copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.backup
        backup: yes

    - name: Ensure that the SSH config file contains desired settings
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "{{ item }}"
        create: yes
      with_items:
        - "LogLevel VERBOSE"
        - "MaxAuthTries 6"
        - "MaxSessions 10"
        - "PermitEmptyPasswords no"
        - "PermitRootLogin no"
      notify: Restart SSH service

    - name: Restart SSH service to apply changes
      systemd:
        name: sshd
        state: restarted
      when: ansible_facts['distribution'] == "Debian" or ansible_facts['distribution'] == "Ubuntu"

  handlers:
    - name: Restart SSH service
      systemd:
        name: sshd
        state: restarted
