---
- name: Stop and remove MySQL container
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_sudo_pass: "{{ lookup('env', 'USER_PASSWORD') }}"
    mysql_container_name: "mariadb_server"  # Name of the MySQL container

  tasks:
    # Check if MySQL container is running
    - name: Check if MySQL container is running
      command: docker ps -q -f name={{ mysql_container_name }}
      register: mysql_ps_check
      changed_when: false
      failed_when: false

    # Stop the MySQL container if it is running
    - name: Stop MySQL container
      docker_container:
        name: "{{ mysql_container_name }}"
        state: stopped
      when: mysql_ps_check.stdout | length > 0

    # Remove the MySQL container if it exists
    - name: Remove MySQL container
      docker_container:
        name: "{{ mysql_container_name }}"
        state: absent
      when: mysql_ps_check.stdout | length > 0
