version: v1.0

name: Run MSSQL Docker in Semaphore

# Define your Docker image and pipeline settings
docker:
  version: '19.03'  # Define the Docker version to use

# Define the pipeline's steps
jobs:
  build_and_run:
    name: Build and Run MSSQL Docker
    docker:
      - image: "docker:19.03.12"  # Docker image used to run the job
        context: /workspace        # Workspace context for Docker commands
    steps:
      - checkout  # Checkout your code (this fetches the Git repository)
      
      # Step 1: Install Docker Compose (if not available)
      - run:
          name: Install Docker Compose
          command: |
            curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            docker-compose --version

      # Step 2: Build the Docker image manually
      - run:
          name: Build Docker Image
          command: |
            docker build -t mssql-server-image .  # Build Docker image from Dockerfile

      # Step 3: Run the container using the built image
      - run:
          name: Run Docker Container
          command: |
            docker run -d -p 1433:1433 --name mssql-server-container \
            -e ACCEPT_EULA=Y \
            -e SA_PASSWORD=${SA_PASSWORD} \
            -v mssql-data:/var/opt/mssql \
            mssql-server-image  # Run the container in detached mode

      # Optional: Step 4: Verify the container is running
      - run:
          name: Verify Running Container
          command: |
            docker ps  # List running containers to confirm it is up

# Optional: Define a notification when the pipeline finishes
notify:
  email:
    recipients:
      - your_email@example.com
