---
- name: Configure server for Semaphore UI with Microsoft SQL Server
  hosts: all
  become: true

  tasks:
    # 1. Ensure firewalld is active and running
    - name: Ensure firewalld is installed
      package:
        name: firewalld
        state: present

    - name: Ensure firewalld is started and enabled
      service:
        name: firewalld
        state: started
        enabled: true

    # 2. Update, upgrade, and clean up packages
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Clean up unused packages
      apt:
        autoremove: yes
        autoclean: yes

    # 3. Open only ports for MariaDB (3306) and SSH (22)
    - name: Open port 3306 for MariaDB
      command: firewall-cmd --zone=public --add-port=3306/tcp --permanent

    - name: Open port 22 for SSH
      command: firewall-cmd --zone=public --add-port=22/tcp --permanent

    - name: Reload firewalld
      service:
        name: firewalld
        state: reloaded

    # 4. Install Microsoft SQL Server 2022
    - name: Install required dependencies for Microsoft SQL Server
      apt:
        name:
          - curl
          - apt-transport-https
          - software-properties-common
        state: present

    - name: Add Microsoft SQL Server GPG key
      command: curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

    - name: Add Microsoft SQL Server APT repository
      command: add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/debian/11/prod $(lsb_release -cs) main"

    - name: Install Microsoft SQL Server 2022
      apt:
        name: mssql-server
        state: present

    # 5. Run mssql-conf setup
    - name: Setup Microsoft SQL Server
      command: /opt/mssql/bin/mssql-conf setup
      args:
        creates: /var/opt/mssql/mssql.conf

    # 6. Ensure that mssql-server is running
    - name: Ensure mssql-server service is running
      service:
        name: mssql-server
        state: started
        enabled: true

    # 7. Create a directory for backups
    - name: Create backup directory for SQL Server
      file:
        path: /var/opt/mssql/backup
        state: directory
        mode: '0755'

    # 8. Create SQL databases
    - name: Create databases on SQL Server
      mssql_db:
        name: "{{ item }}"
        state: present
      loop:
        - Account
        - Authentication
        - CabalCash
        - CabalGuild
        - EventData
        - NetcafeBilling
        - Server01
        - cabalmanager
        - cmt_database

    # 9. Configure backup location (optional: backup location configuration is done in SQL Server itself)
    - name: Set backup location
      command: |
        echo "Backups are configured in SQL Server by default to be in /var/opt/mssql/backup."
      # This is for informational purposes since backup locations are set within the SQL Server configuration

    # 10. Restart MS SQL Server
    - name: Restart mssql-server service
      service:
        name: mssql-server
        state: restarted
