- name: Setup User
  hosts: all
  become: true
  vars:
    admin_user_name: "{{ lookup('env', 'ADMIN_USER_NAME') }}"
    admin_password: "{{ lookup('env', 'ADMIN_USER_PASSWORD') }}"

  tasks:
    - name: Create User
      run:
        command: |
          sudo useradd -m -s /bin/bash {{ admin_user_name }}
          echo "{{ admin_user_name }}:{{ admin_password }}" | sudo chpasswd

    - name: Add Sudo Privileges
      run:
        command: |
          echo "{{ admin_user_name }} ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/{{ admin_user_name }}

    - name: Set Permissions
      run:
        command: |
          sudo chmod -R u+rw /home/{{ admin_user_name }}