---
- name: Set up Python environment and install required Python packages
  hosts: all
  become: true  # Ensure tasks are run with elevated privileges

  tasks:
    # PYTHON ENVIRONMENT AND PACKAGES
    - name: Set up Python environment
      block:
        - name: Create a Python virtual environment
          shell: python3 -m venv /opt/myenv
          args:
            creates: /opt/myenv/bin/activate  # Prevents recreation if it already exists
          become: true
