- name: Setup User
  hosts: all
  become: true
  vars:
    admin_user_name: "{{ lookup('env', 'ADMIN_USER_NAME') }}"
    admin_password: "{{ lookup('env', 'ADMIN_USER_PASSWORD') }}"

  tasks:
    - name: Create User
      user:
        name: "{{ admin_user_name }}"
        shell: /bin/bash
        state: present
        create_home: yes

    - name: Set User Password
      user:
        name: "{{ admin_user_name }}"
        password: "{{ admin_password | password_hash('sha512') }}"

    - name: Add Sudo Privileges
      lineinfile:
        path: /etc/sudoers.d/{{ admin_user_name }}
        line: "{{ admin_user_name }} ALL=(ALL) NOPASSWD:ALL"
        create: yes

    - name: Set Permissions
      file:
        path: /home/{{ admin_user_name }}
        mode: u+rw
        recurse: yes