- name: Set Hostname
  hosts: all
  become: true
  vars:
    new_hostname: "database"  # Define the hostname as a variable

  tasks:
    - name: Set the hostname
      hostname:
        name: "{{ new_hostname }}"

    - name: Ensure the hostname is set correctly (reboot if necessary)
      command: hostnamectl set-hostname "{{ new_hostname }}"
      when: ansible_facts['ansible_hostname'] != new_hostname