- name: Open port 3306 for MariaDB and Enable Firewall
  hosts: all
  become: true
  tasks:

    - name: Install firewalld if not installed
      package:
        name: firewalld
        state: present

    - name: Start firewalld
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Open port 3306 for MariaDB in firewalld
      command: firewall-cmd --zone=public --add-port=3306/tcp --permanent
      notify:
        - Reload firewalld

    - name: Reload firewalld to apply changes
      service:
        name: firewalld
        state: reloaded

    - name: Check if port 3306 is open in firewalld
      command: firewall-cmd --query-port=3306/tcp
      register: port_status
      changed_when: false

    - name: Print port status
      debug:
        msg: "Port 3306 status: {{ port_status.stdout }}"

    - name: Ensure firewalld is active
      command: firewall-cmd --state
      register: firewall_state
      changed_when: false

    - name: Print firewall state
      debug:
        msg: "Firewall state: {{ firewall_state.stdout }}"

  handlers:
    - name: Reload firewalld
      service:
        name: firewalld
        state: reloaded
