---
- name: Install MariaDB prerequisites and core package
  hosts: all
  become: true

  vars:
    mariadb_packages_to_install:
      - mariadb-server          # MariaDB server package
      - mariadb-client          # MariaDB client package
      - libmariadb-dev          # Development libraries for MariaDB

  tasks:
    # Update the package cache
    - name: Update APT package cache
      apt:
        update_cache: yes

    # Install MariaDB packages
    - name: Install MariaDB packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ mariadb_packages_to_install }}"

    # Ensure MariaDB service is installed but not started
    - name: Ensure MariaDB service is installed but not started
      systemd:
        name: mariadb
        state: stopped
        enabled: false
