version: '3.8'

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MARIADB_ROOT_PASSWORD}  # Reference the secret SA_PASSWORD from Semaphore
    ports:
      - "1433:1433"   # Expose port 1433 for remote connections
    networks:
      - mssql-network
    volumes:
      - mssql-data:/var/opt/mssql  # Persist data across container restarts

networks:
  mssql-network:
    driver: bridge

volumes:
  mssql-data:
    driver: local