- name: Restrict SSH and MariaDB access to trusted IPs
  hosts: all
  become: true
  vars:
    # Define trusted IPs, pulling them from environment variables or secrets
    trusted_ips:
      - "{{ lookup('env', 'TRUSTED_IP_1') }}"
      - "{{ lookup('env', 'TRUSTED_IP_2') }}"
      - "{{ lookup('env', 'TRUSTED_IP_3') }}"

  tasks:
    - name: Set default firewall policy to block all incoming connections
      command: firewall-cmd --zone=public --set-target=DROP

    - name: Allow access for trusted IPs for SSH
      command: firewall-cmd --zone=public --add-source="{{ item }}" --permanent
      loop: "{{ trusted_ips }}"

    - name: Allow access for trusted IPs for MariaDB (port 3306)
      command: firewall-cmd --zone=public --add-port=3306/tcp --permanent

    - name: Allow SSH access (port 22) for trusted IPs
      command: firewall-cmd --zone=public --add-port=22/tcp --permanent

    - name: Reload firewalld to apply changes
      service:
        name: firewalld
        state: reloaded
