---
- name: Install prerequisites for MariaDB setup
  hosts: all
  become: true
  become_method: sudo
  become_user: root

  vars:
    ansible_sudo_pass: "{{ lookup('env', 'USER_PASSWORD') }}"
    
    # System packages to install
    packages_to_install:
      - sudo
      - python3-pip
      - python3-dev
      - pkg-config  # Required for building mysqlclient
      - libmariadb-dev # MySQL development libraries
      - build-essential  # Compiler tools needed for mysqlclient

    # Python packages to install
    python_packages_to_install:
      - PyMySQL
      - mysqlclient

  tasks:
    - name: Install system packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages_to_install }}"

    - name: Install Python packages with pipx
      command: pipx install "{{ item }}"
      loop: "{{ python_packages_to_install }}"
