---
- name: Install prerequisites for MariaDB setup
  hosts: all
  become: true
  become_method: sudo
  become_user: root

  vars:
    ansible_sudo_pass: "{{ lookup('env', 'USER_PASSWORD') }}"
    # System packages to install
    packages_to_install:
      - python3-pip
      - python3-venv
      - python3-dev
      - pkg-config  # Required for building mysqlclient
      - libmariadb-dev # MySQL development libraries
      - build-essential  # Compiler tools needed for mysqlclient

    # Python packages to install
    python_packages_to_install:
      - PyMySQL
      - requests

  tasks:
    - name: Install system packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages_to_install }}"

    - name: Create a virtual environment for Python packages
      shell: python3 -m venv /opt/myenv
      args:
        creates: /opt/myenv/bin/activate
      become: true

    - name: Install Python packages in the virtual environment
      pip:
        name: "{{ item }}"
        state: present
        executable: /opt/myenv/bin/pip
      loop: "{{ python_packages_to_install }}"