---
- name: Setup MariaDB container
  hosts: all
  become: true
  vars:
    mariadb_container_name: "mariadb_server"
    mariadb_image: "mariadb:latest"
    mariadb_network_name: "mariadb_network"

  tasks:
    # Pull the latest MariaDB Docker image
    - name: Pull MariaDB Docker image
      docker_image:
        name: "{{ mariadb_image }}"
        source: pull

    # Create a Docker volume for MariaDB data
    - name: Create Docker volume for MariaDB data
      docker_volume:
        name: mariadb_data
        state: present

    # Ensure MariaDB container is started
    - name: Start MariaDB container
      docker_container:
        name: "{{ mariadb_container_name }}"
        image: "{{ mariadb_image }}"
        state: started
        restart_policy: unless-stopped
        env:
          MARIADB_ROOT_PASSWORD: "{{ lookup('env', 'MYSQL_ROOT_PASSWORD') }}"
          MARIADB_DATABASE: "{{ lookup('env', 'MYSQL_DATABASE') }}"
          MARIADB_USER: "{{ lookup('env', 'MYSQL_USER') }}"
          MARIADB_PASSWORD: "{{ lookup('env', 'MYSQL_USER_PASSWORD') }}"
        volumes:
          - mariadb_data:/var/lib/mysql
        ports:
          - "3306:3306"

    # Wait for MariaDB to be accessible on port 3306
    - name: Wait for MariaDB to be accessible
      wait_for:
        host: "127.0.0.1"
        port: 3306
        delay: 10
        timeout: 60
        state: started
