version: v1.0
name: Test Vault Secrets

# Define the pipeline
pipelines:
  - name: Test Vault Access
    agent:
      machine:
        type: e1-standard-2
        os_image: ubuntu2204
    blocks:
      - name: Print Vault Secrets
        task:
          secrets:
            - name: mariadb_secrets  # Replace with your actual secret group name
          environment:
            MYSQL_ROOT_PASSWORD: "{{ secret.mysql_root_password }}"
            MYSQL_DATABASE: "{{ secret.mysql_database }}"
            MYSQL_USER: "{{ secret.mysql_user }}"
            MYSQL_PASSWORD: "{{ secret.mysql_user_password }}"
          jobs:
            - name: Echo Secrets
              commands:
                - echo "Testing Vault Access:"
                - echo "MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD"
                - echo "MYSQL_DATABASE: $MYSQL_DATABASE"
                - echo "MYSQL_USER: $MYSQL_USER"
                - echo "MYSQL_PASSWORD: $MYSQL_PASSWORD"

# Define secrets
secrets:
  - name: asd  # Replace with your secret name in the Semaphore Vault


#---
#- name: Setup MariaDB container
#  hosts: all
#  become: true
#  become_method: sudo
#  become_user: root
#
#  vars:
#    mariadb_container_name: "mariadb_server"
#    mariadb_root_password: "{{ lookup('env', 'MARIADB_ROOT_PASSWORD') }}"
#    mariadb_database: "{{ lookup('env', 'MARIADB_DATABASE') }}"
#    mariadb_user: "{{ lookup('env', 'MARIADB_USER') }}"
#    mariadb_user_password: "{{ lookup('env', 'MARIADB_USER_PASSWORD') }}"
#    mariadb_image: "mariadb:latest"
#    mariadb_network_name: "mariadb_network"
#    ansible_python_interpreter: /opt/myenv/bin/python
#
#  tasks:
#    # Pull the latest MariaDB Docker image
#    - name: Pull the latest MariaDB Docker image
#      docker_image:
#        name: "{{ mariadb_image }}"
#        source: pull
#
#    # Create a Docker volume for MariaDB data
#    - name: Create a Docker volume for MariaDB data
#      docker_volume:
#        name: mariadb_data
#        state: present
#
#    # Create a custom Docker network for MariaDB
#    - name: Create custom Docker network for MariaDB
#      docker_network:
#        name: "{{ mariadb_network_name }}"
#        driver: bridge
#        state: present
#
#    # Ensure MariaDB container is started
#    - name: Start MariaDB container
#      docker_container:
#        name: "{{ mariadb_container_name }}"
#        image: "{{ mariadb_image }}"
#        state: started
#        restart_policy: unless-stopped
#        env:
#          MARIADB_ROOT_PASSWORD: "{{ mariadb_root_password }}"
#          MARIADB_DATABASE: "{{ mariadb_database }}"
#          MARIADB_USER: "{{ mariadb_user }}"
#          MARIADB_PASSWORD: "{{ mariadb_user_password }}"
#        volumes:
#          - mariadb_data:/var/lib/mysql
#        networks:
#          - name: "{{ mariadb_network_name }}"
#        ports:
#          - "3306:3306"
#
#    # Wait for MariaDB to be accessible on port 3306
#    - name: Wait for MariaDB to be accessible
#      wait_for:
#        host: "127.0.0.1"
#        port: 3306
#        delay: 10
#        timeout: 60
#        state: started
#
#    # Grant remote access to the MariaDB user
#    - name: Grant remote access to the MariaDB user
#      mysql_user:
#        name: "{{ mariadb_user }}"
#        password: "{{ mariadb_user_password }}"
#        host: "%"
#        priv: "*.*:ALL"
#        state: present
#        login_user: root
#        login_password: "{{ mariadb_root_password }}"
