---
- name: Setup MariaDB container
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
    mariadb_container_name: "mariadb_server"
    mariadb_root_password: "{{ lookup('env', 'MYSQL_ROOT_PASSWORD') }}"
    mariadb_database: "{{ lookup('env', 'MYSQL_DATABASE') }}"
    mariadb_user: "{{ lookup('env', 'MYSQL_USER') }}"
    mariadb_user_password: "{{ lookup('env', 'MYSQL_USER_PASSWORD') }}"
    mariadb_image: "mariadb:latest"
    mariadb_network_name: "mariadb_network"

  tasks:
    - name: Install required Python libraries
      apt:
        name:
          - python3-pip
          - python3-dev
          - libmariadb-dev
        state: present

    - name: Install PyMySQL Python library
      pip:
        name: PyMySQL
        state: present
        executable: pip3
    
    # Pull the latest MariaDB Docker image
    - name: Pull the latest MariaDB Docker image
      docker_image:
        name: "{{ mariadb_image }}"
        source: pull

    # Create a Docker volume for MariaDB data
    - name: Create a Docker volume for MariaDB data
      docker_volume:
        name: mariadb_data
        state: present

    # Create a custom Docker network for MariaDB
    - name: Create custom Docker network for MariaDB
      docker_network:
        name: "{{ mariadb_network_name }}"
        driver: bridge
        state: present

    # Start MariaDB container with the necessary environment variables
    - name: Start MariaDB container
      docker_container:
        name: "{{ mariadb_container_name }}"
        image: "{{ mariadb_image }}"
        state: started
        restart_policy: unless-stopped
        env:
          MARIADB_ROOT_PASSWORD: "{{ mariadb_root_password }}"
          MARIADB_DATABASE: "{{ mariadb_database }}"
          MARIADB_USER: "{{ mariadb_user }}"
          MARIADB_PASSWORD: "{{ mariadb_user_password }}"
        volumes:
          - mariadb_data:/var/lib/mysql
        networks:
          - name: "{{ mariadb_network_name }}"
        ports:
          - "3306:3306"
        command:
          - "--bind-address=0.0.0.0"
          - "--skip-name-resolve"

    # Wait for MariaDB to be accessible on port 3306
    - name: Wait for MariaDB to be accessible
      wait_for:
        host: "127.0.0.1"
        port: 3306
        delay: 10
        timeout: 60
        state: started

    # Grant remote access to the MariaDB user
    - name: Grant remote access to the MariaDB user
      mysql_user:
        name: "{{ mariadb_user }}"
        password: "{{ mariadb_user_password }}"
        host: "%"
        priv: "*.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Validate MariaDB connectivity
      shell: |
        mysqladmin ping -h127.0.0.1 -P3306 -u"{{ mariadb_user }}" -p"{{ mariadb_user_password }}"
      register: mariadb_ping
      ignore_errors: true

    - name: Debug MariaDB connectivity result
      debug:
        var: mariadb_ping
