---
- name: Update and Upgrade Packages, Install Sudo
  hosts: all
  become: true

  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes