---
- name: Update and Upgrade Packages, Install Sudo
  hosts: all
  become_method: sudo
  become_user: root
  become: true  # Ensure we have root privileges to manage sudoers and other actions
  vars:
    user_name: "{{ lookup('vault', 'asd.asd') }}"  # Fetch username from Ansible Vault

  tasks:
#    - name: Update the package list
#      apt:
#        update_cache: yes
#
#    - name: Upgrade all packages
#      apt:
#        upgrade: dist
#        autoremove: yes

    - name: Print from Vault
      debug:
        msg: "The USER_NAME is: {{ asd }}"

#---
#- name: Update and Upgrade Packages, Install Sudo
#  hosts: all
#  become_method: sudo
#  become_user: root
#  become: true  # Ensure we have root privileges to manage sudoers and other actions
#  vars:
#    user_name: "{{ lookup('env', 'USER_NAME') }}"  # Fetch username from environment
#    user_password: "{{ lookup('env', 'USER_PASSWORD') }}"  # Fetch password from environment
#
#  tasks:
#    - name: Update the package list
#      apt:
#        update_cache: yes
#
#    - name: Upgrade all packages
#      apt:
#        upgrade: dist
#        autoremove: yes